# Development version - builds images from source code
# Use this for development and testing changes
version: '3.8'

services:
  tilehub-app:
    build: .
    image: madroots/tilehub-app:test
    depends_on:
      - tilehub-db
    environment:
      - DB_HOST=tilehub-db
      - DB_NAME=tilehubdb
      - DB_USER=tilehubuser
      - DB_PASS=tilehubpass
    volumes:
      - uploads_data:/var/www/html/uploads
      - ./app:/var/www/html
    networks:
      - tilehub-network

  tilehub-web:
    build: 
      context: .
      dockerfile: ./custom-images/nginx/Dockerfile
    image: madroots/tilehub-nginx:test
    ports:
      - "5200:80"
    volumes:
      - uploads_data:/var/www/html/uploads
      - ./app:/var/www/html
    depends_on:
      - tilehub-app
    networks:
      - tilehub-network

  tilehub-db:
    build: ./custom-images/mariadb
    image: madroots/tilehub-mariadb:test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tilehubdb
      MYSQL_USER: tilehubuser
      MYSQL_PASSWORD: tilehubpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tilehub-network

volumes:
  db_data:
  uploads_data:

networks:
  tilehub-network:
    driver: bridge