services:
  tilehub-app:
    build: .
    image: madroots/tilehub:latest
    volumes:
      - ./app:/var/www/html
    depends_on:
      - tilehub-db
    environment:
      - DB_HOST=tilehub-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - tilehub-network

  tilehub-web:
    image: nginx:latest
    ports:
      - "5200:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - tilehub-app
    networks:
      - tilehub-network

  tilehub-db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./docker/mariadb-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - tilehub-network

volumes:
  db_data:

networks:
  tilehub-network:
    driver: bridge
