services:
  tilehub-app:
    image: madroots/tilehub-app:latest
    depends_on:
      - tilehub-db
    environment:
      - DB_HOST=tilehub-db
      - DB_NAME=tilehubdb
      - DB_USER=tilehubuser
      - DB_PASS=tilehubpass
    networks:
      - tilehub-network

  tilehub-web:
    image: madroots/tilehub-nginx:latest
    ports:
      - "5200:80"
    depends_on:
      - tilehub-app
    networks:
      - tilehub-network

  tilehub-db:
    image: madroots/tilehub-mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tilehubdb
      MYSQL_USER: tilehubuser
      MYSQL_PASSWORD: tilehubpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tilehub-network

volumes:
  db_data:

networks:
  tilehub-network:
    driver: bridge
